// <auto-generated />
namespace Intranet.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class first_push : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(first_push));
        
        string IMigrationMetadata.Id
        {
            get { return "201709221537504_first_push"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
